business_values:
- id: bv_prise_en_charge
  name: Prise en charge patient
  process: Accueil administratif, vérification des prescriptions, enregistrement DPI/RIS,
    consentement
  feared_event: Impossibilité d'accueillir et d'enregistrer les patients, entraînant
    des retards de prise en charge.
  severity: 4
- id: bv_acquisition
  name: Acquisition des images
  process: Réalisation de l'examen par le manipulateur, acquisition et transfert DICOM
    vers le PACS
  feared_event: Arrêt des équipements d'imagerie ou impossibilité de transférer les
    images, arrêt de la production de soins.
  severity: 4
- id: bv_interpretation
  name: Interprétation et compte rendu
  process: Visualisation PACS, rédaction CR dans le RIS, signature électronique, envoi
    MSSanté
  feared_event: Indisponibilité des images ou du RIS retardant le diagnostic, ou erreur
    de compte rendu affectant la santé du patient.
  severity: 4
- id: bv_teleradiologie
  name: Téléradiologie
  process: Transfert chiffré VPN, interprétation à distance, retour CR signé
  feared_event: Interception ou indisponibilité du flux de téléradiologie compromettant
    les gardes et urgences.
  severity: 4
- id: bv_archivage
  name: Archivage légal
  process: Stockage long terme, réplication sur site distant
  feared_event: Perte définitive des historiques médicaux.
  severity: 4
